# ---------------------------------------------------------------------------
# Convert.py
# Created on: Thu May 16 2013 04:13:29 PM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------
# data input: an Access file with all stations in tables.
# 1) Use ArcGIS to extract the tables to dbf files to get a list of table name. However, dbf file do not have time information.
# 2) Use the list to generate a python script to extract the tables in Access to text file.
 
# Import system modules
import sys, string, os, arcgisscripting
 
# Create the Geoprocessor object
gp = arcgisscripting.create()
 
# Load required toolboxes...
gp.AddToolbox("C:/working/PGMN/20130417/PGMN Precip Data for Portal 201305/Additional Conversion - Generic Tools.tbx")
 
 
# Local variables...
filelist = ["024","039","043","054","062","063","066","080","083","088","092","093","095","109","113","123","124","140","165","187","190","192","206","207","215","220","221","232","242","250","278","281","286","293","305","307","321","322","331","349","350","358","373","383","392","399","431","453","454","460","487","496"]
for file in filelist:
    v024_csv = "C:\\working\\PGMN\\20130417\\PGMN Precip Data for Portal 201305\\" + file + ".csv"
    v024 = "C:\\working\\PGMN\\20130417\\PGMN Precip Data for Portal 201305\\PGMN Precip Data for Portal 201305.mdb\\" + file
 
    # Process: Table To Excel...
    gp.TableToExcel_conversion2(v024, v024_csv, "CSV")